version: '3.7'

services:
  java-app:
    image: nclcloudcomputing/javabenchmarkapp
    ports:
      - "80:8080"
#    ports:
#      - target: 8080 # port inside container
#        published: 80 # Exposed port
#        protocol: tcp
#        mode: ingress # for swarm mode
    deploy:
      mode: replicated
      replicas: 2

  swarm-viz:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - target: 8080
        published: 88
        protocol: tcp
        mode: host

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor