version: '3.7'

services:
  java-app:
    image: nclcloudcomputing/javabenchmarkapp
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 2

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - target: 8080
        published: 88
        protocol: tcp
        mode: host

  mongo-db:
    image: mongo:latest
    ports:
      - "3306:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor